sudo: false
dist: trusty
language: c++
compiler:
  - gcc
addons:
  apt:
    packages:
    - libreadline6-dev
    - libncurses5-dev
    - perl
    - clang
    - g++-mingw-w64-i686
env:
 - BRBASE=3.16 BRPVD=master
 - BRBASE=3.16 BRPVD=master CMPLR=clang
 - BRBASE=3.16 BRPVD=master USR_CXXFLAGS=-std=c++11
 - BRBASE=3.16 BRPVD=master USR_CXXFLAGS=-std=c++11 CMPLR=clang
 - BRBASE=3.16 BRPVD=master WINE=32 TEST=NO STATIC=YES
 - BRBASE=3.16 BRPVD=master WINE=32 TEST=NO STATIC=NO
 - BRBASE=3.15 BRPVD=master
 - BRBASE=3.14 BRPVD=master
install:
 - ./ci/travis-prepare.sh
script:
 - ./ci/travis-build.sh
